### ISSUE TITLE
Some texts are not translatable

### ISSUE THREAD

**Issue by sh0thub** [rhinstaller/blivet-gui#58]
Hello, I created Slovak translation on zanata, and found that a lot of texts is not translatable. 
For example: 
* Resize
* Modify parents 
* Set mountpoint 
* No pending actions
* Pending actions
* x pending actions
* [127] create device partition xxx (id 123)
* partition icon tooltips - Encrypted device, Empty device, Group device
* icon tooltips - Add new device, Delete selected device, Edit selected device...

I checked source code and found, that some of non-translatable texts are situated in .ui files on folder data/ui/
Please fix, and update pot file to zanata, so everyone can translate all texts in app.

**Comment by vojtechtrefny** [comment]
Thank you for noticing. I forgot to upload new POT file to Zanata for quite a long time, oops.

I have uploaded new POT file to Zanata. I will fix some untranslatable strings that are actually in code (not just old POT file) asap.

**Comment by vojtechtrefny** [comment]
#61 should fix this.

Note that some strings are actually from blivet (or other tools/libraries), not from blivet-gui, (e.g. `[127] create device partition xxx (id 123)` is an action description from blivet). Thank you again for reporting this.

**Comment by sh0thub** [comment]
Hello,
thanks for good work, but still have some problems:

1. Lot of text are now translatable in zanata, but not all (icons description, text like: existing, non-existing, Add? etc). You probably not uploaded latest pot to zanata (I can see only f26-branch on zanata, not master. It would be better to create master version tag in zanata and than branched, actually there are only branched versions, so translators could translate master and branched).

2. You are right, some texts (pending actions) are from blivet, for example "create device partition", but i have translated all blivet versions in zanata and still some text are not translated. Probably blivet pot file in zanata is also outdated. I checked in fedora 26, a still the same problem. I will report a bug on blivet repo for this problem.

**Comment by vojtechtrefny** [comment]
> Lot of text are now translatable in zanata, but not all (icons description, text like: existing, non-existing, Add? etc). You probably not uploaded latest pot to zanata 

That's because I didn't merge #61 (I merged it now, I had to wait for a review).

> (I can see only f26-branch on zanata, not master. It would be better to create master version tag in zanata and than branched, actually there are only branched versions, so translators could translate master and branched).

Yeah, branches on Zanata are little bit messy. I'll probably close the older branches on Zanata and keep just the f26 one (and rename it to master). I don't even have a special branch for f26 here on GH.

> You are right, some texts (pending actions) are from blivet, for example "create device partition", but i have translated all blivet versions in zanata and still some text are not translated. Probably blivet pot file in zanata is also outdated. I checked in fedora 26, a still the same problem. I will report a bug on blivet repo for this problem.

POT file for blivet should be up-to-date -- newest is only one week old. I'll check blivet code if these "actions" strings are translatable.

**Comment by vojtechtrefny** [comment]
New POT file is in Zanata. I hope everything (from blivet-gui) is now translatable. Sorry it took a little bit longer.

**Comment by sh0thub** [comment]
Thanks for great job, everything I find in blivet-gui is now translatable. Thank you again for resolving.
